language: node_js
node_js:
  - --lts # LTS
  - node # Current
env:
  - JEST_TIMEOUT: 30000
before_script: npm run lint
script: npm test -- --coverage --ci
after_script: codecov
cache:
  directories:
    - $HOME/.npm
